// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkILrX0QFS0MRhDFes7LMFhDOWHibIyYI',
    appId: '1:656311448145:web:ea6941c43604287382be70',
    messagingSenderId: '656311448145',
    projectId: 'iot-fuel-monitoring-app',
    authDomain: 'iot-fuel-monitoring-app.firebaseapp.com',
    storageBucket: 'iot-fuel-monitoring-app.firebasestorage.app',
    measurementId: 'G-1R0JYQ1QCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXHv4haUCGhlWd41B3AHmO2AcUVV3uCWo',
    appId: '1:656311448145:android:1ec338fe2cd986f482be70',
    messagingSenderId: '656311448145',
    projectId: 'iot-fuel-monitoring-app',
    storageBucket: 'iot-fuel-monitoring-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyGhkwA-r2nR9QXYZBURA0c8_O0RC-Dho',
    appId: '1:656311448145:ios:5f3ffde30fa5a81282be70',
    messagingSenderId: '656311448145',
    projectId: 'iot-fuel-monitoring-app',
    storageBucket: 'iot-fuel-monitoring-app.firebasestorage.app',
    iosBundleId: 'com.example.fuelMonitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyGhkwA-r2nR9QXYZBURA0c8_O0RC-Dho',
    appId: '1:656311448145:ios:5f3ffde30fa5a81282be70',
    messagingSenderId: '656311448145',
    projectId: 'iot-fuel-monitoring-app',
    storageBucket: 'iot-fuel-monitoring-app.firebasestorage.app',
    iosBundleId: 'com.example.fuelMonitoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkILrX0QFS0MRhDFes7LMFhDOWHibIyYI',
    appId: '1:656311448145:web:4513ebe983c1647c82be70',
    messagingSenderId: '656311448145',
    projectId: 'iot-fuel-monitoring-app',
    authDomain: 'iot-fuel-monitoring-app.firebaseapp.com',
    storageBucket: 'iot-fuel-monitoring-app.firebasestorage.app',
    measurementId: 'G-FBTR9VP99B',
  );

}